
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 01 15:45:50 CST 2013
//----------------------------------------------------

package lex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 16;
  public static final int RIGHT_PAREN = 24;
  public static final int INT = 2;
  public static final int SND = 33;
  public static final int MINUS = 14;
  public static final int END_OF_PROGRAM = 38;
  public static final int AND = 17;
  public static final int APPEND = 26;
  public static final int LT = 11;
  public static final int FUN = 34;
  public static final int TAIL = 31;
  public static final int NIL = 29;
  public static final int IN = 22;
  public static final int OR = 18;
  public static final int COMMA = 25;
  public static final int PLUS = 13;
  public static final int ASSIGN = 28;
  public static final int IF = 4;
  public static final int EOF = 0;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int NEGATION = 20;
  public static final int EQ = 10;
  public static final int HEAD = 30;
  public static final int TIMES = 15;
  public static final int ARROW = 35;
  public static final int ELSE = 6;
  public static final int WHILE = 8;
  public static final int LET = 21;
  public static final int THEN = 5;
  public static final int END = 7;
  public static final int LEFT_PAREN = 23;
  public static final int SEQUENCE = 27;
  public static final int FALSE = 37;
  public static final int UNARY_MINUS = 19;
  public static final int FST = 32;
  public static final int GT = 12;
  public static final int VAR = 3;
  public static final int DO = 9;
}

